name: Build and Push Docker image

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Определяем теги, которые будем использовать
      - name: Define Docker tags
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/my-bot
          tags: |
            type=semver,pattern={{version}}  # Использует версию из Git-тега (например, v1.2.3 -> 1.2.3)
            type=semver,pattern={{major}}.{{minor}} # Например, v1.2.3 -> 1.2
            type=semver,pattern={{major}}      # Например, v1.2.3 -> 1
            type=raw,value=latest,enable={{is_main}} # Добавляем 'latest' только если это push в main

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}